baseurl = "https://zhaohuabing.com"
title = "Huabing Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "zhaohuabings-blog"
googleAnalytics = "UA-109223766-1"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "赵化冰的博客 | Zhaohuabing Blog"
  description = "赵化冰，程序员, 开源爱好者，生活探险家 | 这里是 赵化冰 的博客，与你一起发现更大的世界。"
  keyword = "赵化冰, zhaohuabing, Zhaohuabing, , 赵化冰的网络日志, 赵化冰的博客, Zhaohuabing Blog, 博客, 个人网站, 互联网, Web, 云原生, PaaS, Istio, Kubernetes, 微服务, Microservice"
  slogan = "路在脚下，心向远方"

  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("

  # leancloud storage for page view counter
  page_view_conter = true
  leancloud_app_id = "Xu5MAnXL360Ms89vMVnWBjuq-gzGzoHsz"
  leancloud_app_key = "efUYEefAc2eIPBRO59PRERQC"

  # algolia site search
  algolia_search = true
  algolia_appId = "WM4BEY1UDN"
  algolia_indexName = "blog"
  algolia_apiKey = "090c4a77b8bd4b8d2f2c1262afbc4be2"

  # Sidebar settings
  sidebar_about_description = "Engineer @Tencent Cloud, Open Source Enthusiast and Life Adventurer"
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/zhaohuabing.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true
  featured_condition_size = 2

  # Baidu Analytics
  ba_track_id = "a1d96090e4189c0376251fb043da7be5"

  # We need a proxy to access Disqus api in China
  disqus_proxy = "https://disqusapi.zhaohuabing.com"
  disqus_site = "https://zhaohuabing.com"

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles
  reward = false
  reward_guide = "嗯，这篇文章对我有用，鼓励一下..."

  friends = true
  bookmarks = true
  about_me = true

  [params.social]
  rss            = true
  email          = "zhaohuabing@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  twitter        = "https://twitter.com/zhaohuabing"
  linkedin       = "https://www.linkedin.com/in/zhaohuabing"
  #stackoverflow  = "https://stackoverflow.com/users/2306565/huabing-zhao"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/zhaohuabing"
  wechat         = "https://zhaohuabing.com/img/wechat_qrcode.jpg"
  medium         = "https://medium.com/@zhaohuabing"
  #pinterest     = "full profile url in pinterest"

  [[params.friend_link]]
  title = "Linda的博客"
  href =  "https://zhaozhihan.com"

  [[params.bookmark_link]]
  title = "medium"
  href =  "https://medium.com/@zhaohuabing"
  [[params.bookmark_link]]
  title = "pexels"
  href = "https://www.pexels.com"
  [[params.bookmark_link]]
  title = "van gogh"
  href = "https://www.vangoghmuseum.nl/en/collection?q="

  [[params.addtional_menus]]
  title =  "BOOKS"
  href =  "/top/books/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
