[build]
[build.environment]
HUGO_VERSION = "0.96.0"
GO_VERSION = "1.18"
[[redirects]]
  from = "/learning-envoy/*"
  to = "https://hilarious-faloodeh-b9f59a.netlify.app/:splat"
  status = 200
  force = true
